event_inherited()
draw_set_halign(fa_left)
draw_set_valign(fa_middle)
draw_set_color(make_color_rgb(201, 211, 228))
draw_text(x + sprite_width * 0.5 + 468, y, string(round(global.musicVolume * 100)) + "%")
draw_set_halign(fa_left)
draw_set_valign(fa_top)
