event_inherited()
draw_set_halign(fa_left)
draw_set_valign(fa_middle)
draw_set_color(make_color_rgb(210, 216, 228))
draw_text(x + sprite_width * 0.5 + 470, y, string(round(global.sfxVolume * 100)) + "%")
draw_set_halign(fa_left)
draw_set_valign(fa_top)
